### ISSUE TITLE
batch normalisation 16fp?

### ISSUE THREAD

**Issue by hengck23** [drnikolaev/caffe#13]
I am porting some caffe code to fp16. I face problem with batch normalisation (BN). It seems that cudnn doesn't support BN for fp16. The caffe engine seems prone to overflow if i use fp 16. Do you have a solution?

Thanks.

**Comment by hujie-frank** [comment]
I have the same problem, the value in mean and var of all the cudnn_BN_layer come to be "nan" in forward stage.

**Comment by ghost** [comment]
Hi, did you guys figure out?

**Comment by drnikolaev** [comment]
@hengck23 @hujiePKU @RupeshD - NVIDIA/caffe-0.16 does it all now
