### ISSUE TITLE
It's a bug in elementwise/sum start from 0.16

### ISSUE THREAD

**Issue by CFAndy** [drnikolaev/caffe#14]
The diff error in my topology was caused by the commted ShareDIff.
change back to old style walk-around the issue.
Just FYI. 
  case EltwiseParameter_EltwiseOp_SUM:
        if (coeffs_[i] == 1.F) {
 	  Btype* bottom_diff = bottom[i]->mutable_gpu_diff<Btype>();
          //bottom[i]->ShareDiff(*top[0]);
          caffe_copy(count, top_diff, bottom_diff);
        } else {
          Btype* bottom_diff = bottom[i]->mutable_gpu_diff<Btype>();
          caffe_gpu_scale(count, Btype(coeffs_[i]), top_diff, bottom_diff);
        }
        break;

**Comment by drnikolaev** [comment]
Hi @CFAndy , could you please share the model you use? Other ones seem to work fine with this optimization.
