### ISSUE TITLE
 ERROR on digits server when using bvlc_cub_v4_v5

### ISSUE THREAD

**Issue by engharat** [drnikolaev/caffe#7]
Hi,
I' have compiled successfully the nvcaffe bvlc_cub_v4_v5 version, but when trying to execute digits I get the following error:

`ERROR: Library at "libcaffe.so.1.0.0-rc3" does not have expected suffix "-nv". Are you using the NVIDIA/caffe fork?
Invalid input
`
In nvcaffe/build/lib dir I see `libcaffe.a  libcaffe.so  libcaffe.so.1.0.0-rc3
`

I can run successfully nvcaffe of master branch and also nvcaffe 0.15 by drnikolaev, but I fail to run on that drnikolaev bvlc_cub_v4_v5 version. I have just update DIGITS to the last version but the error is still here.
Any hints?
thanks

**Comment by engharat** [comment]
Ok I suppose to have found what the problem is. Despite being a nvidia/caffe fork, the bvlc_cub_v4_v5 is not a "nvcaffe" but is a "caffe" so not suitable for digits!

**Comment by drnikolaev** [comment]
Correct. Please use nvcaffe for DIGITS. This bvlc_cub_v4_v5 branch was created for PR #3919
